# Generated by Django 5.0.7 on 2024-08-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla',
            name='value',
        ),
        migrations.AddField(
            model_name='tabla',
            name='check_restocking',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='item_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='pull',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
