# Generated by Django 5.0.7 on 2024-08-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starbucks', '0002_remove_tabla_value_tabla_check_restocking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabla',
            name='shelf_life',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
